### ISSUE TITLE
"Famous" value generators

### ISSUE THREAD

**Issue by jeffh** [jeffh/Fox#26]
For more comprehensive coverage, it would be useful to provide famous value generators. These generators prioritize "famous" values (minimum/maximum values) at a higher probability than can be achieved through normal generation:

 - [x] Integer (min, max)
 - [x] PositiveInteger (min, max)
 - [x] NegativeInteger (min, max)
 - [x] StrictPositiveInteger (min, max)
 - [x] StrictNegativeInteger (min, max)
 - [x] Float (min, max, inf, -inf, NaN)
 - [x] Double (min, max, inf, -inf, NaN)
 - [x] DecimalNumber (min, max, NaN)

This can be accomplished with `FOXFrequency` with a 1-10% probability of a generating famous values.

Tests:
- [x] Backfill StrictPositiveInteger tests
- [x] Backfill StrictNegativeInteger tests

Header Docs:
- [x] FamousInteger
- [x] FamousPositiveInteger
- [x] FamousNegativeInteger
- [x] FamousStrictPositiveInteger
- [x] FamousStrictNegativeInteger
- [x] FamousFloat
- [x] FamousDouble
- [x] FamousDecimalNumber

Docs:
- [x] FamousInteger
- [x] FamousPositiveInteger
- [x] FamousNegativeInteger
- [x] FamousStrictPositiveInteger
- [x] FamousStrictNegativeInteger
- [x] FamousFloat
- [x] FamousDouble
- [x] FamousDecimalNumber

**Comment by chadbrewbaker** [comment]
Ok. So with three composed generators f(g(h()), the outer generator f() is shrunk and the inner generator values g(h()) stay fixed?

**Comment by jeffh** [comment]
It depends on how the generators are implemented. Each generator can customize the shrinking behavior as needed. f can choose to shrink the tree produced by g. The same applies for g(h()).

This makes something like `FOXGenMap` and `FOXMap` different:

- `FOXGenMap` applies a function on the rose tree and returns a (possibly new) rose tree.
- `FOXMap` applies a function to each element in the rose tree.

So you could create a generator that suppresses shrinking by:

```objc
// coding from the waist, may not actually compile
id<FOXGenerator> NoShrinking(id<FOXGenerator> generator) {
    return FOXGenMap(generator, ^FOXRoseTree *(FOXRoseTree *generatedTree) {
        return [[FOXRoseTree alloc] initWithValue:generatedTree.value];
    });
}
```
