### ISSUE TITLE
Passing test takes long time to finish (> 30 sec)

### ISSUE THREAD

**Issue by niilohlin** [jeffh/Fox#45]
I tried to run the following code using XCode 7 both on a physical device and on a simulated ios device.

    id<FOXGenerator> generator = FOXArray(FOXAlphabeticalString());
    
    FOXAssert(FOXForAll(generator, ^BOOL(NSArray<NSString *> *array) {
        return array.count >= 0;
    }));

It ran in 38 seconds. Is this expected behaviour? Failing tests finish in < 1 sec.

**Comment by niilohlin** [comment]
Fixed it by lowering FOXOptions.numberOfTests

**Comment by jeffh** [comment]
String generation hasn't been optimized yet. Collection generation tends to be much slower than atomic values
